from __future__ import annotations

"""Column names and other schema-related constants."""

COLUMN_FILE_PATH = "文件路径"
COLUMN_ACTIVITY_NAME = "活动名称"
COLUMN_STATUS = "状态"
COLUMN_MATCH_TYPE = "匹配类型"
COLUMN_MATCH_VALUE = "匹配值"
COLUMN_STUDENT_ID = "学号"
COLUMN_STUDENT_NAME = "姓名"
COLUMN_SNIPPET = "证据片段"
COLUMN_MATCH_COUNT = "匹配次数"
CLASS_TAG_LABEL = "班级关键词"

DETAIL_SHEET_NAME = "明细列表"
PER_ACTIVITY_SHEET_NAME = "按活动汇总"
PER_PERSON_SHEET_NAME = "按学生汇总"
CLASS_TAG_SHEET_NAME = "班级关键词命中"

STUDENT_MATCH_TYPES = {"学号", "姓名", "学号+姓名"}
COLUMN_ACTIVITY_FILE_COUNT = "涉及文件数"
COLUMN_MATCH_TOTAL = "匹配总计"
COLUMN_PERSON_ACTIVITY_COUNT = "参与活动数"
COLUMN_PERSON_ACTIVITY_LIST = "活动列表"

__all__ = [
    "COLUMN_FILE_PATH",
    "COLUMN_ACTIVITY_NAME",
    "COLUMN_STATUS",
    "COLUMN_MATCH_TYPE",
    "COLUMN_MATCH_VALUE",
    "COLUMN_STUDENT_ID",
    "COLUMN_STUDENT_NAME",
    "COLUMN_SNIPPET",
    "COLUMN_MATCH_COUNT",
    "CLASS_TAG_LABEL",
    "DETAIL_SHEET_NAME",
    "PER_ACTIVITY_SHEET_NAME",
    "PER_PERSON_SHEET_NAME",
    "CLASS_TAG_SHEET_NAME",
    "STUDENT_MATCH_TYPES",
    "COLUMN_ACTIVITY_FILE_COUNT",
    "COLUMN_MATCH_TOTAL",
    "COLUMN_PERSON_ACTIVITY_COUNT",
    "COLUMN_PERSON_ACTIVITY_LIST",
]
